// pub
const PUB_URLS = [
    "/base/turn/queryTurnRecordList",
    "/base/turn/export",
    "/base/turnexamaudit/list",
    "/base/turnexamaudit/export",
    "/base/turnexamaudit/detail",
    "/base/turnexamaudit/add",
    "/base/turnexamaudit/remove",
    "/base/turnexamaudititem/remove",
    "/base/turnexamaudititem/listAll",
    "/base/turnexamaudititem/addList",
    "/base/turnexamaudititem/getStdTurnExamAuditItem",
    "/base/turnExamInfo/queryScoreList",
    "/base/turninterstdplan/list",
    "/base/turninterstdplan/finishList",
    "/base/turninterstdplan/export",
    "/base/turninterstdplan/exportFinishList",
    "/base/turninterstdplan/",
    "/base/turnplan/changeBaseDoctorEdit",
    "/base/turnplan/getTurnPlanPermission",
    "/base/turnplandetail/listTurnResident",
    "/base/turnscoreconf/getList",
    "/base/turnscoreconf/getScoreValue",
    "/base/turnscoreconf/saveScoreConf",
    "/base/turnscoreconf/getLatestConf",
    "/base/turnscore/editTurnScore",
    "/base/turnscore/getScoreDetail/",
    "/base/turnscore/isEdit/",
    "/base/turnscoredetail/getBigCaseScore",
    "/base/turnscorehistory/list",
    "/base/turnScore/userList",
    "/base/turnScore/getPlanScore/",
    "/base/turnScore/getAllTurnScore/",
    "/base/evaluateReport/list",
    "/base/scoringtemplate/listTemplate",
    "/base/turninterstdplan/finishList",
    "/base/largeMedicalRecord/auditList",
    "/base/scoringtemplatedept/getScoringTemplateDept",
    "/base/evaluateReport/add",
    "/base/largeMedicalRecord/update",
    "/base/largeMedicalRecord/detail/",
    "/base/scoringtemplatedept/getScoringTemplateDept",
    "/base/turninterstdplan/finishList",
    "/base/turninterstdplan/finishList",
    "/base/largeMedicalRecord",
    "/base/info/getSeiid",
    "/base/commpara/getListByCode",
   ]



module.exports = PUB_URLS;